// NOVA AI Filter — natural-language → structured filter spec applied across
// Dashboard / Scanner / Web Picks. Spec is generated by the `nova-filter`
// edge function (Lovable AI tool-calling), then reduced over each pick list.
//
// Capital handling: STRICT — premium × 100 ≤ budget. A pick that doesn't
// fit one contract is dropped, full stop (per user spec).
import { useEffect, useState } from "react";

export type NovaFilterSpec = {
  budget?: number | null;                 // total $ available for one contract
  riskBuckets?: ("safe" | "mild" | "aggressive" | "lottery")[]; // empty = all
  bias?: ("bullish" | "bearish" | "neutral")[];
  optionTypes?: ("call" | "put")[];
  strategies?: string[];                  // substring match against strategy field
  symbols?: string[];                     // restrict to these tickers
  excludeSymbols?: string[];
  expiryFrom?: string | null;             // ISO yyyy-mm-dd inclusive
  expiryTo?: string | null;               // ISO yyyy-mm-dd inclusive
  maxDte?: number | null;
  minDte?: number | null;
  minScore?: number | null;
  minAnnualized?: number | null;          // %
  excludeEarnings?: boolean;              // drop picks with earnings ≤ 7d
  rationale?: string;                     // human-readable echo of what NOVA understood
};

export const EMPTY_SPEC: NovaFilterSpec = {};

// ── pub/sub store ────────────────────────────────────────────────────────────
const KEY = "nova_filter_spec";
const listeners = new Set<(s: NovaFilterSpec) => void>();

function read(): NovaFilterSpec {
  if (typeof window === "undefined") return EMPTY_SPEC;
  try {
    const raw = window.sessionStorage.getItem(KEY);
    return raw ? JSON.parse(raw) : EMPTY_SPEC;
  } catch { return EMPTY_SPEC; }
}

export function setNovaFilter(spec: NovaFilterSpec) {
  if (typeof window !== "undefined") window.sessionStorage.setItem(KEY, JSON.stringify(spec));
  listeners.forEach((l) => l(spec));
}

export function clearNovaFilter() { setNovaFilter(EMPTY_SPEC); }

export function useNovaFilter(): [NovaFilterSpec, (s: NovaFilterSpec) => void, () => void] {
  const [spec, setLocal] = useState<NovaFilterSpec>(() => read());
  useEffect(() => {
    const cb = (s: NovaFilterSpec) => setLocal(s);
    listeners.add(cb);
    return () => { listeners.delete(cb); };
  }, []);
  return [spec, setNovaFilter, clearNovaFilter];
}

export function isFilterActive(s: NovaFilterSpec): boolean {
  return !!(
    s.budget || s.riskBuckets?.length || s.bias?.length || s.optionTypes?.length ||
    s.strategies?.length || s.symbols?.length || s.excludeSymbols?.length ||
    s.expiryFrom || s.expiryTo || s.maxDte != null || s.minDte != null ||
    s.minScore != null || s.minAnnualized != null || s.excludeEarnings
  );
}

// ── generic pick shape used by the applier ──────────────────────────────────
export interface FilterablePick {
  symbol: string;
  strategy?: string;
  riskBucket?: "safe" | "mild" | "aggressive" | "lottery";
  bias?: "bullish" | "bearish" | "neutral";
  optionType?: "call" | "put";
  expiration?: string;       // ISO date
  dte?: number | null;
  premium?: number | null;   // per-share premium (× 100 = contract cost)
  score?: number | null;
  annualized?: number | null;
  earningsInDays?: number | null;
}

export function pickMatchesFilter(p: FilterablePick, s: NovaFilterSpec): boolean {
  if (!isFilterActive(s)) return true;

  if (s.symbols?.length && !s.symbols.map((x) => x.toUpperCase()).includes(p.symbol.toUpperCase())) return false;
  if (s.excludeSymbols?.length && s.excludeSymbols.map((x) => x.toUpperCase()).includes(p.symbol.toUpperCase())) return false;

  if (s.riskBuckets?.length && p.riskBucket && !s.riskBuckets.includes(p.riskBucket)) return false;
  if (s.bias?.length && p.bias && !s.bias.includes(p.bias)) return false;
  if (s.optionTypes?.length && p.optionType && !s.optionTypes.includes(p.optionType)) return false;

  if (s.strategies?.length && p.strategy) {
    const strat = p.strategy.toLowerCase();
    if (!s.strategies.some((x) => strat.includes(x.toLowerCase()))) return false;
  }

  if (s.expiryFrom && p.expiration && p.expiration < s.expiryFrom) return false;
  if (s.expiryTo && p.expiration && p.expiration > s.expiryTo) return false;

  if (s.maxDte != null && p.dte != null && p.dte > s.maxDte) return false;
  if (s.minDte != null && p.dte != null && p.dte < s.minDte) return false;

  if (s.minScore != null && p.score != null && p.score < s.minScore) return false;
  if (s.minAnnualized != null && p.annualized != null && p.annualized < s.minAnnualized) return false;

  if (s.excludeEarnings && p.earningsInDays != null && p.earningsInDays <= 7) return false;

  // STRICT capital gate — per-contract cost = premium × 100 (US equity options).
  if (s.budget != null && p.premium != null) {
    const contractCost = p.premium * 100;
    if (contractCost > s.budget) return false;
  }

  return true;
}
